### ISSUE TITLE
[Auth] User should be redirected to the last URL before redirected to SSO

### ISSUE THREAD

**Issue by adalberht** [metricsui/web#24]
Case:
- User access `/dashboard`
- User get redirected to SSO
- User log in successfully but they are redirected back to the landing page

Expectation:
- After SSO login, user should be redirected back to `/dashboard`

Solution:
- `handleLogin()` implementation should pass current hash route as well (not only domain)

**Comment by adalberht** [comment]
Reopening again since the SSO seems to only supports origin

**Comment by wisnuprama** [comment]
Config issue, closed
