### ISSUE TITLE
Automatic dark mode when browser supports media prefers-color-scheme

### ISSUE THREAD

**Issue by wisnuprama** [metricsui/web#6]
**Is your feature request related to a problem? Please describe.**;

Need to toggle it by myself. A starting point for myself in this project.

**Describe the solution you'd like**

As we're already using JS way to have dark mode, we will continue to use it. So to support color scheme media CSS, we will query via JS and if the query result matches with `dark` value then we will automatically apply dark mode [[doc](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia)]

```js
window.matchMedia('prefers-color-scheme: dark').matches ? 'dark' : 'light'
```

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by adalberht** [comment]
👍  for this
Thanks nu! Will review soon
